/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Product;
import javax.swing.JOptionPane;

/**
 *
 * @author ajaygoel
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    private Product product;
    public CreateJPanel(Product product) {
        initComponents();
        this.product=product;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CreateBtn = new javax.swing.JLabel();
        NameBtn = new javax.swing.JLabel();
        PriceBtn = new javax.swing.JLabel();
        AvailibilityNumberBtn = new javax.swing.JLabel();
        DescriptionBtn = new javax.swing.JLabel();
        NameTctField = new javax.swing.JTextField();
        PriceTextField = new javax.swing.JTextField();
        AvailibiltyNumberTxtField = new javax.swing.JTextField();
        DescriptionTxtField = new javax.swing.JTextField();
        Createbt = new javax.swing.JButton();

        CreateBtn.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        CreateBtn.setText("Create");

        NameBtn.setText("Name:");

        PriceBtn.setText("Price:");

        AvailibilityNumberBtn.setText("Availibilty Number:");

        DescriptionBtn.setText("Description:");

        Createbt.setText("Create");
        Createbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreatebtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PriceBtn)
                    .addComponent(NameBtn)
                    .addComponent(AvailibilityNumberBtn)
                    .addComponent(DescriptionBtn))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CreateBtn)
                            .addComponent(NameTctField)
                            .addComponent(PriceTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(AvailibiltyNumberTxtField))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Createbt)
                            .addComponent(DescriptionTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CreateBtn)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NameBtn)
                            .addComponent(NameTctField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PriceBtn)
                            .addComponent(PriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(AvailibilityNumberBtn))
                    .addComponent(AvailibiltyNumberTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DescriptionBtn)
                    .addComponent(DescriptionTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Createbt)
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CreatebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreatebtActionPerformed
        // TODO add your handling code here:
        //Binding the user input to the product object
        product.setName(NameTctField.getText());
        product.setPrice(PriceTextField.getText());
        product.setAvailNum(AvailibiltyNumberTxtField.getText());
        product.setDescription(DescriptionTxtField.getText());
        
        //Prompt user that product successfully created
        JOptionPane.showMessageDialog(null,"Product successfully created");
        
    }//GEN-LAST:event_CreatebtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AvailibilityNumberBtn;
    private javax.swing.JTextField AvailibiltyNumberTxtField;
    private javax.swing.JLabel CreateBtn;
    private javax.swing.JButton Createbt;
    private javax.swing.JLabel DescriptionBtn;
    private javax.swing.JTextField DescriptionTxtField;
    private javax.swing.JLabel NameBtn;
    private javax.swing.JTextField NameTctField;
    private javax.swing.JLabel PriceBtn;
    private javax.swing.JTextField PriceTextField;
    // End of variables declaration//GEN-END:variables
}
