/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.CarProfile;
import Business.CarProfileHistory;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

//import jxl.Cell;
//import jxl.Sheet;
//import jxl.Workbook;
//import jxl.read.biff.BiffException;
//import java.io.File;
//import java.io.IOException;

/**
 *
 * @author ajaygoel
 */
public class CreatePanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePanel
     */
   private CarProfileHistory cph;
   public CreatePanel(CarProfileHistory cph) {
        initComponents();
        this.cph = cph;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        isAvalBtnGroup = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        Manufacturerlbl = new javax.swing.JLabel();
        ManufacturerTxtField = new javax.swing.JTextField();
        Carlbl = new javax.swing.JLabel();
        CarTxtField = new javax.swing.JTextField();
        ManYrlbl = new javax.swing.JLabel();
        ManufactureYrTxtField = new javax.swing.JTextField();
        Noseatslbl = new javax.swing.JLabel();
        SeatsTxtField = new javax.swing.JTextField();
        colorlbl = new javax.swing.JLabel();
        ColorTxtField = new javax.swing.JTextField();
        mainDatelbl = new javax.swing.JLabel();
        DateTxtField = new javax.swing.JTextField();
        carnolbl = new javax.swing.JLabel();
        CarNoTxtField = new javax.swing.JTextField();
        Chasisnolbl = new javax.swing.JLabel();
        ChasisNoTxtField = new javax.swing.JTextField();
        mobnolbl = new javax.swing.JLabel();
        MobNoTxtField = new javax.swing.JTextField();
        SaveBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        YesRadio = new javax.swing.JRadioButton();
        ProgressBar = new javax.swing.JProgressBar();
        Progress = new javax.swing.JButton();
        NoBtn = new javax.swing.JRadioButton();

        jButton1.setText("jButton1");

        jRadioButton1.setText("jRadioButton1");

        jLabel1.setText("Create Car Profile");

        Manufacturerlbl.setText("Manufacturer");

        Carlbl.setText("Car");

        ManYrlbl.setText("Manufacture Year");

        Noseatslbl.setText("No. of Seats");

        colorlbl.setText("Color");

        mainDatelbl.setText("Maintenance Date");

        carnolbl.setText("Car No.");

        Chasisnolbl.setText("Chasis No.");

        mobnolbl.setText("Mobile No. driver");

        SaveBtn.setText("Save");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Availibility");

        isAvalBtnGroup.add(YesRadio);
        YesRadio.setText("click - yes");

        ProgressBar.setStringPainted(true);

        Progress.setText("Check Progress");
        Progress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProgressActionPerformed(evt);
            }
        });

        isAvalBtnGroup.add(NoBtn);
        NoBtn.setText("click- No");
        NoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(colorlbl)
                            .addComponent(carnolbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ColorTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                            .addComponent(CarNoTxtField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ManYrlbl)
                            .addComponent(Manufacturerlbl))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ManufactureYrTxtField)
                            .addComponent(ManufacturerTxtField)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mobnolbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MobNoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ChasisNoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Chasisnolbl)
                            .addComponent(Progress))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SaveBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Noseatslbl)
                            .addComponent(Carlbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SeatsTxtField)
                            .addComponent(CarTxtField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mainDatelbl)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DateTxtField)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(YesRadio)
                                    .addComponent(NoBtn))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(ProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Manufacturerlbl)
                    .addComponent(Carlbl)
                    .addComponent(ManufacturerTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CarTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ManYrlbl)
                    .addComponent(Noseatslbl)
                    .addComponent(SeatsTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ManufactureYrTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colorlbl)
                    .addComponent(DateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ColorTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainDatelbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carnolbl)
                    .addComponent(CarNoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(NoBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Chasisnolbl)
                    .addComponent(ChasisNoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YesRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mobnolbl)
                    .addComponent(MobNoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveBtn)
                    .addComponent(Progress))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        // TODO add your handling code here:
        
        try
        {
        String manufacturer = ManufacturerTxtField.getText();
        if(manufacturer.matches(".*\\d.*"))
        {
           JOptionPane.showMessageDialog(null,"Please enter the valid manufacturer name with no digits");   
        }
        else if(manufacturer.equals(null)||manufacturer.equals(""))
        {
           JOptionPane.showMessageDialog(null,"Please enter the manufacturer name to create a profile");   
        }  
        else if(manufacturer.trim().length()==0)
        {
           JOptionPane.showMessageDialog(null,"Please enter the manufacturer name to create a profile");   
        }  
        else
           manufacturer = (ManufacturerTxtField.getText());
        
        
        
        String car_name=CarTxtField.getText();
        
         if(car_name.matches(".*\\d.*"))
        {
           JOptionPane.showMessageDialog(null,"Please enter the valid car name with no digits");   
        }
        else if(car_name.equals(null)||car_name.equals(""))
        {
           JOptionPane.showMessageDialog(null,"Please enter the car name to create a profile");   
        }  
        else if(car_name.trim().length()==0)
        {
           JOptionPane.showMessageDialog(null,"Please enter the car name to create a profile");   
        }  
        else
           car_name = (CarTxtField.getText());
       
        
        int manufacture_yr=Integer.parseInt(ManufactureYrTxtField.getText());
        if(manufacture_yr==0)
            JOptionPane.showMessageDialog(null,"Please enter the valid Year");
        else
            manufacture_yr=Integer.parseInt(ManufactureYrTxtField.getText());

        
        int mob_no= Integer.parseInt(MobNoTxtField.getText());
        int seats= Integer.parseInt(SeatsTxtField.getText());
        
        if(seats==0)
            JOptionPane.showMessageDialog(null,"Please enter seats carefully");
        else
            seats=Integer.parseInt(SeatsTxtField.getText());
        
        
        String chasis_no=ChasisNoTxtField.getText();
        String maintenance_date=DateTxtField.getText();
        String color=ColorTxtField.getText();
        String car_no=CarNoTxtField.getText();
        String isAval = null;
        
        for(Enumeration<AbstractButton> buttons = isAvalBtnGroup.getElements();
                buttons.hasMoreElements();){
            
            AbstractButton button = buttons.nextElement();
            if(button.isSelected()){
                isAval =button.getText();
            }
        }
        
        Boolean isAvailable = false;
        if(isAval.equals("click - yes"))isAvailable = true;
        
        
                
        //String avail_not=.getText(YesRadio);
        //String profile_image=.getText();
        CarProfile c = cph.addprofile();
        c.setCar_name(car_name);
        c.setManufacturer(manufacturer);
        c.setManufacture_yr(manufacture_yr);
        c.setMaintenance_date(maintenance_date);
        c.setMob_no(mob_no);
        c.setSeats(seats);
        c.setChasis_no(chasis_no);
        c.setColor(color);
        c.setCar_no(car_no);
        c.setAvail_not(isAvailable);
        JOptionPane.showMessageDialog(null,"Profile Added Successfully");
        
        ManufacturerTxtField.setText("");
        CarTxtField.setText("");
        ManufactureYrTxtField.setText("");
        MobNoTxtField.setText("");
        SeatsTxtField.setText("");
        ChasisNoTxtField.setText("");
        DateTxtField.setText("");
        ColorTxtField.setText("");
        CarNoTxtField.setText("");
        }
        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Please enter valid values");
        }
        
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void ProgressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProgressActionPerformed
        // TODO add your handling code here:
       /* 
        if(ManufacturerTxtField.getText()!=null)   
        {
           int value=10;
           ProgressBar.setValue(value);
        }
        
        else if(CarTxtField.getText()!=null)   
        {
           int value=20;
           ProgressBar.setValue(value);
        }
        
        else
        {
            int value=100;
            ProgressBar.setValue(value);
        }
            
        
        
         //   ManufacturerTxtField.setText("");
        //CarTxtField.setText("");
        //ManufactureYrTxtField.setText("");
        //MobNoTxtField.setText("");
        //SeatsTxtField.setText("");
        //ChasisNoTxtField.setText("");
        //DateTxtField.setText("");
        //ColorTxtField.setText("");
        //CarNoTxtField.setText("");
            
            */
    }//GEN-LAST:event_ProgressActionPerformed

    private void NoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CarNoTxtField;
    private javax.swing.JTextField CarTxtField;
    private javax.swing.JLabel Carlbl;
    private javax.swing.JTextField ChasisNoTxtField;
    private javax.swing.JLabel Chasisnolbl;
    private javax.swing.JTextField ColorTxtField;
    private javax.swing.JTextField DateTxtField;
    private javax.swing.JLabel ManYrlbl;
    private javax.swing.JTextField ManufactureYrTxtField;
    private javax.swing.JTextField ManufacturerTxtField;
    private javax.swing.JLabel Manufacturerlbl;
    private javax.swing.JTextField MobNoTxtField;
    private javax.swing.JRadioButton NoBtn;
    private javax.swing.JLabel Noseatslbl;
    private javax.swing.JButton Progress;
    private javax.swing.JProgressBar ProgressBar;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JTextField SeatsTxtField;
    private javax.swing.JRadioButton YesRadio;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JLabel carnolbl;
    private javax.swing.JLabel colorlbl;
    private javax.swing.ButtonGroup isAvalBtnGroup;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel mainDatelbl;
    private javax.swing.JLabel mobnolbl;
    // End of variables declaration//GEN-END:variables
}
