/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.CarProfileHistory;
import Business.CarProfile;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author ajaygoel
 */
public class Search extends javax.swing.JPanel {
    
    
    
    private CarProfileHistory cph;
    String Updated_time;
    public Search(CarProfileHistory cph) {
        initComponents();
        this.cph = cph;
        //populateTable();
    }
    
    public void populateTable()
    {
        DefaultTableModel dtm = (DefaultTableModel)tblCarProfile.getModel();
        dtm.setRowCount(0);
        
        for (CarProfile cp : cph.getCarProfileHistory())
        {
            Object row[] =new Object[4];
            row[0]= cp;
            row[1]= cp.getManufacture_yr();
            row[2]= cp.getSeats();
            row[3]= cp.getCar_no();
            dtm.addRow(row); 
        }
    }
    
     public void populateFilterTable(ArrayList<CarProfile> Car)
    {
        DefaultTableModel dtm = (DefaultTableModel)tblCarProfile.getModel();
        dtm.setRowCount(0);
        
        for (CarProfile cp : Car)
        {
            Object row[] =new Object[4];
            row[0]= cp;
            row[1]= cp.getManufacture_yr();
            row[2]= cp.getSeats();
            row[3]= cp.getCar_no();
            dtm.addRow(row); 
            
        }
    }
     
     /*   public void populateTableNoPassing(CarProfile Car)
    {
        DefaultTableModel dtm = (DefaultTableModel)tblCarProfile.getModel();
        dtm.setRowCount(0);
        
        for (CarProfile cp : Car )
        { 
            Object row[] =new Object[4];
            row[0]= cp;
            row[1]= cp.getManufacture_yr();
            row[2]= cp.getSeats();
            row[3]= cp.getCar_no();
            if(cp.getSeats()>0){
            
            
            dtm.addRow(row); 
            break;
            }
        }
    }*/

    /**
     * Creates new form Search
     */
    public Search() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnGroups = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCarProfile = new javax.swing.JTable();
        btnViewDetails = new javax.swing.JButton();
        BtnUpdate = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ClickAvailableBtn = new javax.swing.JButton();
        Manufacturerlbl = new javax.swing.JLabel();
        ManufacturerTxtField = new javax.swing.JTextField();
        CarTxtField = new javax.swing.JTextField();
        ManYrlbl = new javax.swing.JLabel();
        ManufactureYrTxtField = new javax.swing.JTextField();
        Noseatslbl = new javax.swing.JLabel();
        SeatsTxtField = new javax.swing.JTextField();
        colorlbl = new javax.swing.JLabel();
        ColorTxtField = new javax.swing.JTextField();
        mainDatelbl = new javax.swing.JLabel();
        DateTxtField = new javax.swing.JTextField();
        carnolbl = new javax.swing.JLabel();
        CarNoTxtField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Chasisnolbl = new javax.swing.JLabel();
        ChasisNoTxtField = new javax.swing.JTextField();
        NoBtn = new javax.swing.JRadioButton();
        YesRadio = new javax.swing.JRadioButton();
        mobnolbl = new javax.swing.JLabel();
        MobNoTxtField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        allAvalBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        findCarsMade = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        YearTxtField = new javax.swing.JTextField();
        YearBtn = new javax.swing.JButton();
        CarsCompanyTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        MinTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        MaxTextField = new javax.swing.JTextField();
        SeatsClick = new javax.swing.JButton();
        CarNameBtn = new javax.swing.JButton();
        CarNameTextField = new javax.swing.JTextField();
        carNoBtn = new javax.swing.JButton();
        CarnumberTextField = new javax.swing.JTextField();
        TimeTextField = new javax.swing.JTextField();
        TimeClick = new javax.swing.JButton();

        jLabel1.setText("Search Car Profile");

        tblCarProfile.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Car", "Manufacturer Yr", "No. of Seats", "Car No."
            }
        ));
        jScrollPane2.setViewportView(tblCarProfile);

        btnViewDetails.setText("View Details");
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });

        BtnUpdate.setText("Update");
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });

        jLabel3.setText("Filters:");

        jLabel2.setText("To find first available car");

        ClickAvailableBtn.setText("Click");
        ClickAvailableBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClickAvailableBtnActionPerformed(evt);
            }
        });

        Manufacturerlbl.setText("Manufacturer");

        CarTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarTxtFieldActionPerformed(evt);
            }
        });

        ManYrlbl.setText("Manufacture Year");

        Noseatslbl.setText("No. of Seats");

        colorlbl.setText("Color");

        mainDatelbl.setText("Maintenance Date");

        carnolbl.setText("Car No.");

        jLabel4.setText("Availibility");

        Chasisnolbl.setText("Chasis No.");

        BtnGroups.add(NoBtn);
        NoBtn.setText("click- No");
        NoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoBtnActionPerformed(evt);
            }
        });

        BtnGroups.add(YesRadio);
        YesRadio.setSelected(true);
        YesRadio.setText("click - yes");

        mobnolbl.setText("Mobile No. driver");

        jLabel5.setText("To find all available cars");

        allAvalBtn.setText("Click");
        allAvalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allAvalBtnActionPerformed(evt);
            }
        });

        jLabel6.setText("To find Cars Company");

        findCarsMade.setText("Click");
        findCarsMade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findCarsMadeActionPerformed(evt);
            }
        });

        jLabel7.setText("Car");

        jLabel8.setText("Cars with specified Year");

        YearBtn.setText("Click");
        YearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearBtnActionPerformed(evt);
            }
        });

        CarsCompanyTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarsCompanyTextFieldActionPerformed(evt);
            }
        });

        jLabel9.setText("Enter Seats");

        jLabel10.setText("To Find by Car No.");

        jLabel11.setText("To find by Car Name");

        jLabel12.setText("To find last Updated Time:");

        jLabel14.setText("Min.");

        jLabel15.setText("Max.");

        SeatsClick.setText("Click");
        SeatsClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeatsClickActionPerformed(evt);
            }
        });

        CarNameBtn.setText("Click");
        CarNameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarNameBtnActionPerformed(evt);
            }
        });

        carNoBtn.setText("Click");
        carNoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carNoBtnActionPerformed(evt);
            }
        });

        TimeClick.setText("Click");
        TimeClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimeClickActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addGap(104, 104, 104)
                        .addComponent(CarTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ClickAvailableBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(YearTxtField))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(18, 18, 18)
                                                .addComponent(CarsCompanyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(findCarsMade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, Short.MAX_VALUE)
                                            .addComponent(YearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(allAvalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnViewDetails)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnUpdate))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel9)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel14)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(MinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel15)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(MaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel11)
                                                            .addComponent(jLabel10))
                                                        .addGap(18, 18, 18)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(CarNameTextField)
                                                            .addComponent(CarnumberTextField))))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(SeatsClick, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(carNoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(CarNameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TimeClick, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(249, 249, 249)
                                .addComponent(jLabel1)))))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ManYrlbl)
                                        .addComponent(Manufacturerlbl))
                                    .addGap(15, 15, 15)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ManufactureYrTxtField)
                                        .addComponent(ManufacturerTxtField)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(colorlbl)
                                        .addComponent(carnolbl)
                                        .addComponent(Chasisnolbl)
                                        .addComponent(mobnolbl))
                                    .addGap(16, 16, 16)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(MobNoTxtField)
                                        .addComponent(ChasisNoTxtField)
                                        .addComponent(CarNoTxtField)
                                        .addComponent(ColorTxtField))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Noseatslbl)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(SeatsTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(mainDatelbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(DateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(NoBtn)
                                            .addComponent(YesRadio))))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 39, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(ClickAvailableBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(allAvalBtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnViewDetails)
                            .addComponent(BtnUpdate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel14)
                            .addComponent(MinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(MaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SeatsClick))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(CarsCompanyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(findCarsMade))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(YearTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(YearBtn)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CarnumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(carNoBtn)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CarNameBtn)
                                    .addComponent(CarNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel12)
                                        .addComponent(TimeClick)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(CarTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(116, 116, 116))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(178, 178, 178)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Manufacturerlbl)
                        .addComponent(ManufacturerTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ManYrlbl)
                        .addComponent(Noseatslbl)
                        .addComponent(SeatsTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ManufactureYrTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(colorlbl)
                        .addComponent(DateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ColorTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mainDatelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 46, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(carnolbl)
                                    .addComponent(CarNoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(NoBtn))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Chasisnolbl)
                                .addComponent(ChasisNoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(YesRadio)))
                        .addComponent(jLabel4))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mobnolbl)
                        .addComponent(MobNoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
        // TODO add your handling code here:

        int selectedrow = tblCarProfile.getSelectedRow();
        BtnGroups.clearSelection();

        if(selectedrow>=0)
        {
            CarProfile cp = (CarProfile)tblCarProfile.getValueAt(selectedrow,0);
            
            ManufacturerTxtField.setText(cp.getManufacturer());
            CarTxtField.setText(cp.getCar_name());
            ManufactureYrTxtField.setText(String.valueOf(cp.getManufacture_yr()));
            MobNoTxtField.setText(String.valueOf(cp.getMob_no()));
            SeatsTxtField.setText(String.valueOf(cp.getSeats()));
            ChasisNoTxtField.setText(cp.getChasis_no());
            DateTxtField.setText(cp.getMaintenance_date());
            ColorTxtField.setText(cp.getColor());
            CarNoTxtField.setText(String.valueOf(cp.getCar_no()));
            String isAval = cp.isAvail_not()?"true":"false";
            //String isAval = cp.isAvail_not();
            if(isAval.equals("false")){
                BtnGroups.clearSelection();
                YesRadio.setSelected(false);
                NoBtn.setSelected(true);
            
            }
            else
            {
                BtnGroups.clearSelection();
                YesRadio.setSelected(true);
                NoBtn.setSelected(false);
            }

        }
        else
        JOptionPane.showMessageDialog(null,"Please select any row");

    }//GEN-LAST:event_btnViewDetailsActionPerformed

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
        // TODO add your handling code here:
        int selectedrow = tblCarProfile.getSelectedRow();
        BtnGroups.clearSelection();
        if(selectedrow>0)
        {
            CarProfile cp = (CarProfile)tblCarProfile.getValueAt(selectedrow,0);

            cp.setManufacturer(ManufacturerTxtField.getText());
            cp.setMob_no(Integer.parseInt(MobNoTxtField.getText()));
            cp.setSeats(Integer.parseInt(SeatsTxtField.getText()));
            cp.setCar_name(CarTxtField.getText());
            cp.setChasis_no(ChasisNoTxtField.getText());
            cp.setMaintenance_date(DateTxtField.getText());
            cp.setColor(ColorTxtField.getText());
            cp.setCar_no(CarNoTxtField.getText());

            JOptionPane.showMessageDialog(null,"Record is updated successfully");
            populateTable();
            ManufacturerTxtField.setText("");
            CarTxtField.setText("");
            ManufactureYrTxtField.setText("");
            MobNoTxtField.setText("");
            SeatsTxtField.setText("");
            ChasisNoTxtField.setText("");
            DateTxtField.setText("");
            ColorTxtField.setText("");
            CarNoTxtField.setText("");
            BtnGroups.clearSelection();
        }
        else
        JOptionPane.showMessageDialog(null,"Please select any row");

    }//GEN-LAST:event_BtnUpdateActionPerformed

    private void ClickAvailableBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClickAvailableBtnActionPerformed
        // TODO add your handling code here:
        //CarProfileHistory c = new   CarProfileHistory();
        ArrayList<CarProfile> carProfiles = new ArrayList<>();
        carProfiles = cph.getfirstaval();
        populateFilterTable(carProfiles);
       // populateTableNoPassing(c);
        
        
        
        /*
        ManufacturerTxtField.setText(c.getManufacturer());
        CarTxtField.setText(c.getCar_name());
        ManufactureYrTxtField.setText(String.valueOf(c.getManufacture_yr()));
        MobNoTxtField.setText(String.valueOf(c.getMob_no()));
        SeatsTxtField.setText(String.valueOf(c.getSeats()));
        ChasisNoTxtField.setText(c.getChasis_no());
        DateTxtField.setText(c.getMaintenance_date());
        ColorTxtField.setText(c.getColor());
        CarNoTxtField.setText(String.valueOf(c.getCar_no()));
        String isAval = c.isAvail_not()?"true":"false";
        if(isAval.equals("false")){
            YesRadio.setSelected(false);
            NoBtn.setSelected(true);
            
        }
        else
        {
            BtnGroups.clearSelection();
            YesRadio.setSelected(true);
            NoBtn.setSelected(false);
        }*/
        
        //populateTable();
        

    }//GEN-LAST:event_ClickAvailableBtnActionPerformed

    private void NoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoBtnActionPerformed

    private void allAvalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allAvalBtnActionPerformed
        // TODO add your handling code here:
        ManufacturerTxtField.setText("");
        CarTxtField.setText("");
        ManufactureYrTxtField.setText("");
        MobNoTxtField.setText("");
        SeatsTxtField.setText("");
        ChasisNoTxtField.setText("");
        DateTxtField.setText("");
        ColorTxtField.setText("");
        CarNoTxtField.setText("");
        BtnGroups.clearSelection();
        
        ArrayList<CarProfile> carProfiles = new ArrayList<>();
        carProfiles = cph.getallAvail();
        populateFilterTable(carProfiles);
    

    }//GEN-LAST:event_allAvalBtnActionPerformed

    private void findCarsMadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findCarsMadeActionPerformed
        // TODO add your handling code here:
        
        ManufacturerTxtField.setText("");
        CarTxtField.setText("");
        ManufactureYrTxtField.setText("");
        MobNoTxtField.setText("");
        SeatsTxtField.setText("");
        ChasisNoTxtField.setText("");
        DateTxtField.setText("");
        ColorTxtField.setText("");
        CarNoTxtField.setText("");
        BtnGroups.clearSelection();
        //populateTable();
        
        String Company = CarsCompanyTextField.getText();
        
        if(Company.matches(".*\\d.*"))
           JOptionPane.showMessageDialog(null,"Please enter the valid manufacturer name with no digits");   
        else if(Company.equals(null)||Company.equals(""))
           JOptionPane.showMessageDialog(null,"Please enter the manufacturer name to create a profile");   
        else if(Company.trim().length()==0)
           JOptionPane.showMessageDialog(null,"Please enter the manufacturer name to create a profile");   
        else
           Company = (ManufacturerTxtField.getText());
        
        ArrayList<CarProfile> carProfiles = new ArrayList<>();
        carProfiles = cph.getMadeCar(Company);
        CarsCompanyTextField.setText("");
        populateFilterTable(carProfiles);
        
        
    }//GEN-LAST:event_findCarsMadeActionPerformed

    private void CarTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CarTxtFieldActionPerformed

    private void YearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YearBtnActionPerformed
        // TODO add your handling code here:
        int manufacture_yr=Integer.parseInt(YearTxtField.getText());
        if(manufacture_yr==0)
            JOptionPane.showMessageDialog(null,"Please enter the valid Year");
        else
            manufacture_yr=Integer.parseInt(ManufactureYrTxtField.getText());
        
        ManufacturerTxtField.setText("");
        CarTxtField.setText("");
        ManufactureYrTxtField.setText("");
        MobNoTxtField.setText("");
        SeatsTxtField.setText("");
        ChasisNoTxtField.setText("");
        DateTxtField.setText("");
        ColorTxtField.setText("");
        CarNoTxtField.setText("");
        BtnGroups.clearSelection();
        
        ArrayList<CarProfile> carProfiles = new ArrayList<>();
        carProfiles = cph.getMadeYear(manufacture_yr);
        YearTxtField.setText("");
        populateFilterTable(carProfiles);
        
        
    }//GEN-LAST:event_YearBtnActionPerformed

    private void carNoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carNoBtnActionPerformed
        // TODO add your handling code here:
        
        
        String Car_n =CarnumberTextField.getText();
        
        ManufacturerTxtField.setText("");
        CarTxtField.setText("");
        ManufactureYrTxtField.setText("");
        MobNoTxtField.setText("");
        SeatsTxtField.setText("");
        ChasisNoTxtField.setText("");
        DateTxtField.setText("");
        ColorTxtField.setText("");
        CarNoTxtField.setText("");
        BtnGroups.clearSelection();
        
        ArrayList<CarProfile> carProfiles = new ArrayList<>();
        carProfiles = cph.getCarNumber(Car_n);
        CarnumberTextField.setText("");
        populateFilterTable(carProfiles);
    }//GEN-LAST:event_carNoBtnActionPerformed

    private void CarNameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarNameBtnActionPerformed
        // TODO add your handling code here:
        
        String Car_name =CarNameTextField.getText();
        
         if(Car_name.matches(".*\\d.*"))
           JOptionPane.showMessageDialog(null,"Please enter the valid car name with no digits");   
        else if(Car_name.equals(null)||Car_name.equals(""))
           JOptionPane.showMessageDialog(null,"Please enter the car name to create a profile");   
        else if(Car_name.trim().length()==0)
           JOptionPane.showMessageDialog(null,"Please enter the car name to create a profile");   
        else
           Car_name = (CarTxtField.getText());
        
        ManufacturerTxtField.setText("");
        CarTxtField.setText("");
        ManufactureYrTxtField.setText("");
        MobNoTxtField.setText("");
        SeatsTxtField.setText("");
        ChasisNoTxtField.setText("");
        DateTxtField.setText("");
        ColorTxtField.setText("");
        CarNoTxtField.setText("");
        BtnGroups.clearSelection();
        
        ArrayList<CarProfile> carProfiles = new ArrayList<>();
        carProfiles = cph.getCarName(Car_name);
        CarNameTextField.setText("");
        populateFilterTable(carProfiles);
    }//GEN-LAST:event_CarNameBtnActionPerformed

    private void SeatsClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeatsClickActionPerformed
        // TODO add your handling code here:
        int Min = Integer.parseInt(MinTextField.getText());
        int Max = Integer.parseInt(MaxTextField.getText());
        
        ManufacturerTxtField.setText("");
        CarTxtField.setText("");
        ManufactureYrTxtField.setText("");
        MobNoTxtField.setText("");
        SeatsTxtField.setText("");
        ChasisNoTxtField.setText("");
        DateTxtField.setText("");
        ColorTxtField.setText("");
        CarNoTxtField.setText("");
        BtnGroups.clearSelection();
        ArrayList<CarProfile> carprofiles = new ArrayList<>();
        carprofiles = cph.getCarSeats(Min,Max);
        MinTextField.setText("");
        MaxTextField.setText("");
        populateFilterTable(carprofiles);
        
        
    }//GEN-LAST:event_SeatsClickActionPerformed

    private void TimeClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimeClickActionPerformed
        // TODO add your handling code here:
        Updated_time = cph.update_time();
        TimeTextField.setText(Updated_time);
        
    }//GEN-LAST:event_TimeClickActionPerformed

    private void CarsCompanyTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarsCompanyTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CarsCompanyTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BtnGroups;
    private javax.swing.JButton BtnUpdate;
    private javax.swing.JButton CarNameBtn;
    private javax.swing.JTextField CarNameTextField;
    private javax.swing.JTextField CarNoTxtField;
    private javax.swing.JTextField CarTxtField;
    private javax.swing.JTextField CarnumberTextField;
    private javax.swing.JTextField CarsCompanyTextField;
    private javax.swing.JTextField ChasisNoTxtField;
    private javax.swing.JLabel Chasisnolbl;
    private javax.swing.JButton ClickAvailableBtn;
    private javax.swing.JTextField ColorTxtField;
    private javax.swing.JTextField DateTxtField;
    private javax.swing.JLabel ManYrlbl;
    private javax.swing.JTextField ManufactureYrTxtField;
    private javax.swing.JTextField ManufacturerTxtField;
    private javax.swing.JLabel Manufacturerlbl;
    private javax.swing.JTextField MaxTextField;
    private javax.swing.JTextField MinTextField;
    private javax.swing.JTextField MobNoTxtField;
    private javax.swing.JRadioButton NoBtn;
    private javax.swing.JLabel Noseatslbl;
    private javax.swing.JButton SeatsClick;
    private javax.swing.JTextField SeatsTxtField;
    private javax.swing.JButton TimeClick;
    private javax.swing.JTextField TimeTextField;
    private javax.swing.JButton YearBtn;
    private javax.swing.JTextField YearTxtField;
    private javax.swing.JRadioButton YesRadio;
    private javax.swing.JButton allAvalBtn;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JButton carNoBtn;
    private javax.swing.JLabel carnolbl;
    private javax.swing.JLabel colorlbl;
    private javax.swing.JButton findCarsMade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel mainDatelbl;
    private javax.swing.JLabel mobnolbl;
    private javax.swing.JTable tblCarProfile;
    // End of variables declaration//GEN-END:variables
}
