/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Profile.Profile;
import java.io.File;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author ajaygoel
 */
public class CreateJPanel extends javax.swing.JPanel {
    String Filename = null;
    /**
     * Creates new form CreateJPanel
     */
    private Profile profile;
    public CreateJPanel(Profile profile) {
        initComponents();
        this.profile=profile;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        NameBtn = new javax.swing.JLabel();
        AddressBtn = new javax.swing.JLabel();
        DOBBtn = new javax.swing.JLabel();
        PhoneBtn = new javax.swing.JLabel();
        FaxBtn = new javax.swing.JLabel();
        EmailBtn = new javax.swing.JLabel();
        SSNBtn = new javax.swing.JLabel();
        MedicalBtn = new javax.swing.JLabel();
        HealthBtn = new javax.swing.JLabel();
        BankBtn = new javax.swing.JLabel();
        LicenseBtn = new javax.swing.JLabel();
        VehicleBtn = new javax.swing.JLabel();
        DeviceBtn = new javax.swing.JLabel();
        LinkedBtn = new javax.swing.JLabel();
        InternetBtn = new javax.swing.JLabel();
        BiometricBtn = new javax.swing.JLabel();
        UniqueIdenBtn = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        NameTextField = new javax.swing.JTextField();
        AddressTextField = new javax.swing.JTextField();
        DOBTextField = new javax.swing.JTextField();
        PhoneTextField = new javax.swing.JTextField();
        FaxTextField = new javax.swing.JTextField();
        EmailTxtField = new javax.swing.JTextField();
        MedicalTxtField = new javax.swing.JTextField();
        HealthTxtField = new javax.swing.JTextField();
        BankTxtField = new javax.swing.JTextField();
        LicenseTxtField = new javax.swing.JTextField();
        VehicleTxtField = new javax.swing.JTextField();
        DeviceTxtField = new javax.swing.JTextField();
        LinkedTxtField = new javax.swing.JTextField();
        BiometricTxtField = new javax.swing.JTextField();
        InternetTxtField = new javax.swing.JTextField();
        UniqueTxtField = new javax.swing.JTextField();
        SSNTextField = new javax.swing.JTextField();
        CreateBtn = new javax.swing.JButton();
        Image_btn = new javax.swing.JButton();
        PathTxtField = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Create");

        NameBtn.setText("Name:");

        AddressBtn.setText("Address:");

        DOBBtn.setText("D.O.B(MM/DD/YYYY):");

        PhoneBtn.setText("Phone No.:");

        FaxBtn.setText("Fax No.:");

        EmailBtn.setText("Email:");

        SSNBtn.setText("S.S.N.:");

        MedicalBtn.setText("Medical Rec. No.:");

        HealthBtn.setText("Health No.:");

        BankBtn.setText("Bank Acc. No.:");

        LicenseBtn.setText("License No.:");

        VehicleBtn.setText("Vehicle UDI:");

        DeviceBtn.setText("Device UDI:");

        LinkedBtn.setText("LinkedIn:");

        InternetBtn.setText("Internet Pr. Add.:");

        BiometricBtn.setText("Biometric Identifier:");

        UniqueIdenBtn.setText("Unique Ident. No:");

        jLabel19.setText("For Image:");

        CreateBtn.setText("Create");
        CreateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateBtnActionPerformed(evt);
            }
        });

        Image_btn.setText("Browse:");
        Image_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Image_btnActionPerformed(evt);
            }
        });

        PathTxtField.setText("Path_image");
        PathTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PathTxtFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NameBtn)
                    .addComponent(AddressBtn)
                    .addComponent(DOBBtn)
                    .addComponent(PhoneBtn)
                    .addComponent(FaxBtn)
                    .addComponent(SSNBtn)
                    .addComponent(EmailBtn)
                    .addComponent(MedicalBtn)
                    .addComponent(HealthBtn)
                    .addComponent(BankBtn)
                    .addComponent(LicenseBtn)
                    .addComponent(VehicleBtn)
                    .addComponent(DeviceBtn)
                    .addComponent(LinkedBtn)
                    .addComponent(BiometricBtn)
                    .addComponent(InternetBtn)
                    .addComponent(UniqueIdenBtn))
                .addGap(18, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BiometricTxtField)
                    .addComponent(InternetTxtField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LinkedTxtField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DeviceTxtField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VehicleTxtField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LicenseTxtField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BankTxtField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HealthTxtField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MedicalTxtField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmailTxtField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddressTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DOBTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PhoneTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FaxTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SSNTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(UniqueTxtField))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(CreateBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PathTxtField)
                            .addComponent(Image_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameBtn)
                    .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Image_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddressBtn)
                    .addComponent(AddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PathTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DOBBtn)
                    .addComponent(DOBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneBtn)
                    .addComponent(PhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FaxBtn)
                    .addComponent(FaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailBtn)
                    .addComponent(EmailTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SSNBtn)
                    .addComponent(SSNTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MedicalBtn)
                    .addComponent(MedicalTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HealthBtn)
                    .addComponent(HealthTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BankBtn)
                    .addComponent(BankTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LicenseBtn)
                    .addComponent(LicenseTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VehicleBtn)
                    .addComponent(VehicleTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeviceBtn)
                    .addComponent(DeviceTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LinkedBtn)
                    .addComponent(LinkedTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InternetBtn)
                    .addComponent(InternetTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BiometricBtn)
                    .addComponent(BiometricTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UniqueIdenBtn)
                    .addComponent(UniqueTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CreateBtn))
                .addContainerGap(13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void CreateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateBtnActionPerformed
        // TODO add your handling code here:
        //Binding the user input to the profile of the person
        //profile.setName(NameTextField.getText());
        
        String namecheck =NameTextField.getText();
        if(namecheck.matches(".*\\d.*"))
        {
           JOptionPane.showMessageDialog(null,"Please enter the valid name with no digits");   
        }
        else if(namecheck.equals(null)||namecheck.equals(""))
        {
           JOptionPane.showMessageDialog(null,"Please enter the name to create a profile");   
        }  
        else if(namecheck.trim().length()==0)
        {
           JOptionPane.showMessageDialog(null,"Please enter the name to create a profile");   
        }  
        else
           profile.setName(NameTextField.getText());
        
        profile.setGeo_data(AddressTextField.getText());
        profile.setDob(DOBTextField.getText());
      //  profile.setTel_no(PhoneTextField.getText());
        
        String Tel = PhoneTextField.getText();
        int tel1 = Tel.length();
        
        int flag = 0;
        if(tel1<10||tel1>10)
        {
            flag = 1;
            JOptionPane.showMessageDialog(null,"Please enter the 10 digit Phone No.");
        }
        else
           profile.setTel_no(PhoneTextField.getText());
        
        
        profile.setFax_no(FaxTextField.getText());
        //profile.setEmail(EmailTxtField.getText());
        
        String Emailcheck = EmailTxtField.getText();
        Pattern pattern = Pattern.compile("^(.+)@(.+)$");
        Matcher matcher = pattern.matcher(Emailcheck);
        boolean characterFound = matcher.find();
        
        if(characterFound)
            profile.setEmail(EmailTxtField.getText());
        else
            JOptionPane.showMessageDialog(null,"Please enter the valid email id");
            
       // profile.setSsn(SSNTextField.getText());
        
        String SSN = SSNTextField.getText();
        int n = SSN.length();
        if(n<10||n>10)
        {
            flag = 1;
            JOptionPane.showMessageDialog(null,"Please enter the 10 digit SSN No.");
        }
        else
            profile.setSsn(SSNTextField.getText());

        profile.setMedical_no(MedicalTxtField.getText());
        profile.setBenificiary_no(HealthTxtField.getText());
        profile.setAccount_no(BankTxtField.getText());
        profile.setLiscence_no(LicenseTxtField.getText());
        profile.setVehical_uvi(VehicleTxtField.getText());
        profile.setDevice_udi(DeviceTxtField.getText());
        profile.setLinked_in(LinkedTxtField.getText());
        profile.setIp_address(InternetTxtField.getText());
        profile.setBiometric_identifier(BiometricTxtField.getText());
        profile.setUnique_identification(UniqueTxtField.getText());
        //profile.setProfile_image(ImageTxtField.getText());
        
        //prompt user that product was successfuly created
        if(flag==0)
            JOptionPane.showMessageDialog(null,"Profile Created Successfully");
        else
            JOptionPane.showMessageDialog(null,"Please enter complete data");
        
    }//GEN-LAST:event_CreateBtnActionPerformed

    private void Image_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Image_btnActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        Filename = f.getAbsolutePath();
        PathTxtField.setText(Filename);
        profile.setProfile_image(PathTxtField.getText());
        
    }//GEN-LAST:event_Image_btnActionPerformed

    private void PathTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PathTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PathTxtFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressBtn;
    private javax.swing.JTextField AddressTextField;
    private javax.swing.JLabel BankBtn;
    private javax.swing.JTextField BankTxtField;
    private javax.swing.JLabel BiometricBtn;
    private javax.swing.JTextField BiometricTxtField;
    private javax.swing.JButton CreateBtn;
    private javax.swing.JLabel DOBBtn;
    private javax.swing.JTextField DOBTextField;
    private javax.swing.JLabel DeviceBtn;
    private javax.swing.JTextField DeviceTxtField;
    private javax.swing.JLabel EmailBtn;
    private javax.swing.JTextField EmailTxtField;
    private javax.swing.JLabel FaxBtn;
    private javax.swing.JTextField FaxTextField;
    private javax.swing.JLabel HealthBtn;
    private javax.swing.JTextField HealthTxtField;
    private javax.swing.JButton Image_btn;
    private javax.swing.JLabel InternetBtn;
    private javax.swing.JTextField InternetTxtField;
    private javax.swing.JLabel LicenseBtn;
    private javax.swing.JTextField LicenseTxtField;
    private javax.swing.JLabel LinkedBtn;
    private javax.swing.JTextField LinkedTxtField;
    private javax.swing.JLabel MedicalBtn;
    private javax.swing.JTextField MedicalTxtField;
    private javax.swing.JLabel NameBtn;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JTextField PathTxtField;
    private javax.swing.JLabel PhoneBtn;
    private javax.swing.JTextField PhoneTextField;
    private javax.swing.JLabel SSNBtn;
    private javax.swing.JTextField SSNTextField;
    private javax.swing.JLabel UniqueIdenBtn;
    private javax.swing.JTextField UniqueTxtField;
    private javax.swing.JLabel VehicleBtn;
    private javax.swing.JTextField VehicleTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
