/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Profile.Profile;
import java.awt.BorderLayout;
import java.awt.Image;

/**
 *
 * @author ajaygoel
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    public ViewJPanel(Profile profile) {
        initComponents();
        dispayprofile(profile);
    }

    
    private void dispayprofile(Profile profile)
    {
        String profileName=profile.getName();
        NameTextField.setText(profileName);
        
        String profileaddress=profile.getGeo_data();
        AddressTextField.setText(profileaddress);
        
        String profileDOB=profile.getDob();
        DOBTextField.setText(profileDOB);
        
        String profilePhone=profile.getTel_no();
        PhoneTextField.setText(profilePhone);
        
        String profileFax=profile.getFax_no();
        FaxTextField.setText(profileFax);
        
        String profileEmail=profile.getEmail();
        EmailTxtField.setText(profileEmail);
        
        String profileSSN=profile.getSsn();
        SSNTextField.setText(profileSSN);
        
        String profilemedical=profile.getMedical_no();
        MedicalTxtField.setText(profilemedical);
        
        String profilehealth=profile.getBenificiary_no();
        HealthTxtField.setText(profilehealth);
        
        String profilebank=profile.getAccount_no();
        BankTxtField.setText(profilebank);
        
        String profilelicense=profile.getLiscence_no();
        LicenseTxtField.setText(profilelicense);
        
        String profilevehicle=profile.getVehical_uvi();
        VehicleTxtField.setText(profilevehicle);
        
        String profiledevice=profile.getDevice_udi();
        DeviceTxtField.setText(profiledevice);
        
        String profilelinked=profile.getLinked_in();
        LinkedTxtField.setText(profilelinked);
        
        String profileInternet=profile.getIp_address();
        InternetTxtField.setText(profileInternet);
        
        String profilebiometric=profile.getBiometric_identifier();
        BiometricTxtField.setText(profilebiometric);
        
        String profileUnique=profile.getUnique_identification();
        UniqueTxtField.setText(profileUnique);
        
        String profileimage =profile.getProfile_image();
        PathTxtField.setText(profileimage);
                
        
       // .setText(profileimage);
        //javax.swing.ImageIcon myimg =new javax.swing.ImageIcon(profileimage);
        //javax.swing.JLabel ShowImg = new javax.swing.JLabel("", myimg, javax.swing.JLabel.CENTER);
        //imagePanel =new javax.swing.JPanel(new BorderLayout());
        //imagePanel.add(ShowImg, BorderLayout.CENTER);
        
        
        //javax.swing.JLabel ShowImg = new javax.swing.JLabel(new javax.swing.ImageIcon(profileimage));
        //imagePanel  = new BorderLayout.Center;
        //imagePanel.add(ShowImg, BorderLayout.CENTER);
        //add(imagePanel, BorderLayout.CENTER);
        
        javax.swing.ImageIcon image = new javax.swing.ImageIcon(new javax.swing.ImageIcon(profileimage).getImage().getScaledInstance(100, 100, Image.SCALE_DEFAULT));
        ShowImg.setIcon(image);
        
        
      //  ImageTxtField
                
      
       
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        NameBtn = new javax.swing.JLabel();
        NameTextField = new javax.swing.JTextField();
        ShowImg = new javax.swing.JLabel();
        AddressBtn = new javax.swing.JLabel();
        AddressTextField = new javax.swing.JTextField();
        DOBBtn = new javax.swing.JLabel();
        DOBTextField = new javax.swing.JTextField();
        PhoneBtn = new javax.swing.JLabel();
        PhoneTextField = new javax.swing.JTextField();
        FaxBtn = new javax.swing.JLabel();
        FaxTextField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        EmailBtn = new javax.swing.JLabel();
        EmailTxtField = new javax.swing.JTextField();
        SSNBtn = new javax.swing.JLabel();
        SSNTextField = new javax.swing.JTextField();
        MedicalBtn = new javax.swing.JLabel();
        MedicalTxtField = new javax.swing.JTextField();
        HealthBtn = new javax.swing.JLabel();
        HealthTxtField = new javax.swing.JTextField();
        BankBtn = new javax.swing.JLabel();
        BankTxtField = new javax.swing.JTextField();
        LicenseBtn = new javax.swing.JLabel();
        LicenseTxtField = new javax.swing.JTextField();
        VehicleBtn = new javax.swing.JLabel();
        VehicleTxtField = new javax.swing.JTextField();
        DeviceBtn = new javax.swing.JLabel();
        DeviceTxtField = new javax.swing.JTextField();
        LinkedBtn = new javax.swing.JLabel();
        LinkedTxtField = new javax.swing.JTextField();
        InternetBtn = new javax.swing.JLabel();
        InternetTxtField = new javax.swing.JTextField();
        BiometricBtn = new javax.swing.JLabel();
        BiometricTxtField = new javax.swing.JTextField();
        UniqueIdenBtn = new javax.swing.JLabel();
        UniqueTxtField = new javax.swing.JTextField();
        PathTxtField = new javax.swing.JTextField();
        imagetest = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("View");

        NameBtn.setText("Name:");

        ShowImg.setText("Image:");

        AddressBtn.setText("Address:");

        DOBBtn.setText("D.O.B:");

        PhoneBtn.setText("Phone No.:");

        FaxBtn.setText("Fax No.:");

        jLabel20.setText("Browse");

        EmailBtn.setText("Email:");

        SSNBtn.setText("S.S.N.:");

        MedicalBtn.setText("Medical Rec. No.:");

        HealthBtn.setText("Health No.:");

        BankBtn.setText("Bank Acc. No.:");

        LicenseBtn.setText("License No.:");

        VehicleBtn.setText("Vehicle UDI:");

        DeviceBtn.setText("Device UDI:");

        LinkedBtn.setText("LinkedIn:");

        InternetBtn.setText("Internet Pr. Add.:");

        BiometricBtn.setText("Biometric Identifier:");

        UniqueIdenBtn.setText("Unique Ident. No:");

        PathTxtField.setText("Path_image");

        imagetest.setText("imagetest");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NameBtn)
                    .addComponent(AddressBtn)
                    .addComponent(DOBBtn)
                    .addComponent(PhoneBtn)
                    .addComponent(FaxBtn)
                    .addComponent(SSNBtn)
                    .addComponent(EmailBtn)
                    .addComponent(MedicalBtn)
                    .addComponent(HealthBtn)
                    .addComponent(BankBtn)
                    .addComponent(LicenseBtn)
                    .addComponent(VehicleBtn)
                    .addComponent(DeviceBtn)
                    .addComponent(LinkedBtn)
                    .addComponent(BiometricBtn)
                    .addComponent(InternetBtn)
                    .addComponent(UniqueIdenBtn))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BiometricTxtField)
                    .addComponent(InternetTxtField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LinkedTxtField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DeviceTxtField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VehicleTxtField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LicenseTxtField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BankTxtField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HealthTxtField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MedicalTxtField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmailTxtField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddressTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DOBTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PhoneTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FaxTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SSNTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(UniqueTxtField))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addComponent(PathTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ShowImg, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(112, 112, 112))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(imagetest))))
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NameBtn)
                            .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddressBtn)
                            .addComponent(AddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DOBBtn)
                            .addComponent(DOBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PhoneBtn)
                            .addComponent(PhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ShowImg, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FaxBtn)
                    .addComponent(FaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(PathTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailBtn)
                    .addComponent(EmailTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SSNBtn)
                    .addComponent(SSNTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MedicalBtn)
                    .addComponent(MedicalTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imagetest))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HealthBtn)
                    .addComponent(HealthTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BankBtn)
                    .addComponent(BankTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LicenseBtn)
                    .addComponent(LicenseTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VehicleBtn)
                    .addComponent(VehicleTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeviceBtn)
                    .addComponent(DeviceTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LinkedBtn)
                    .addComponent(LinkedTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InternetBtn)
                    .addComponent(InternetTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BiometricBtn)
                    .addComponent(BiometricTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UniqueIdenBtn)
                    .addComponent(UniqueTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressBtn;
    private javax.swing.JTextField AddressTextField;
    private javax.swing.JLabel BankBtn;
    private javax.swing.JTextField BankTxtField;
    private javax.swing.JLabel BiometricBtn;
    private javax.swing.JTextField BiometricTxtField;
    private javax.swing.JLabel DOBBtn;
    private javax.swing.JTextField DOBTextField;
    private javax.swing.JLabel DeviceBtn;
    private javax.swing.JTextField DeviceTxtField;
    private javax.swing.JLabel EmailBtn;
    private javax.swing.JTextField EmailTxtField;
    private javax.swing.JLabel FaxBtn;
    private javax.swing.JTextField FaxTextField;
    private javax.swing.JLabel HealthBtn;
    private javax.swing.JTextField HealthTxtField;
    private javax.swing.JLabel InternetBtn;
    private javax.swing.JTextField InternetTxtField;
    private javax.swing.JLabel LicenseBtn;
    private javax.swing.JTextField LicenseTxtField;
    private javax.swing.JLabel LinkedBtn;
    private javax.swing.JTextField LinkedTxtField;
    private javax.swing.JLabel MedicalBtn;
    private javax.swing.JTextField MedicalTxtField;
    private javax.swing.JLabel NameBtn;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JTextField PathTxtField;
    private javax.swing.JLabel PhoneBtn;
    private javax.swing.JTextField PhoneTextField;
    private javax.swing.JLabel SSNBtn;
    private javax.swing.JTextField SSNTextField;
    private javax.swing.JLabel ShowImg;
    private javax.swing.JLabel UniqueIdenBtn;
    private javax.swing.JTextField UniqueTxtField;
    private javax.swing.JLabel VehicleBtn;
    private javax.swing.JTextField VehicleTxtField;
    private javax.swing.JLabel imagetest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel20;
    // End of variables declaration//GEN-END:variables
}
